/* employee view */
DROP VIEW IF EXISTS employeeExcelView;
CREATE VIEW employeeExcelView AS SELECT
em.id employeePrimaryId,
em.employeeId employeeId,
em.employeeFirstName employeeFirstName,
em.employeeMiddleName employeeMiddleName,
em.employeeLastName employeeLastName,
em.employeeGender employeeGender,
em.employeeDOB employeeDOB,
em.employeeType employeeType,
em.employeeHOZonal employeeHOZonal,
dep.deptName deptName,
dg.desigName desigName,
dg.desigLevel desigLevel,

ad.addressAddln1 addressAddln1,
ad.addressAddln2 addressAddln2,
ad.addressCity addressCity,
ad.addressDistprov addressDistprov,
ad.addressState addressState,
ad.addressPinzip addressPinzip,
ad.addressCountry addressCountry,

oad.addressAddln1 oaddressAddln1,
oad.addressAddln2 oaddressAddln2,
oad.addressCity oaddressCity,
oad.addressDistprov oaddressDistprov,
oad.addressState oaddressState,
oad.addressPinzip oaddressPinzip,
oad.addressCountry oaddressCountry,

em.employeeBloodGroup employeeBloodGroup,
em.employeeMobileNo employeeMobileNo,
em.employeeAlterNateMobileNo employeeAlterNateMobileNo,
em.employeeEmailID employeeEmailID,
em.employeeAlternateEmailID employeeAlternateEmailID,
em.employeeDateofJoining employeeDateofJoining,
em.employeeContractStartDate employeeContractStartDate,
em.employeeContractEndDate employeeContractEndDate,
em.employeeConsolidatedSalary,
em.employeeTotalSalary,
em.employeeSalaryEffDate,
em.employeeSalaryType,
em.employeeBasic,
em.employeeHRA,
em.employeeBasketAllowance,
em.contractEmployeeConsolidatedSalary,
em.contractEmployeeSalaryEffDate,
em.contractEmployeeTotalSalary,
em.contractEmployeeBasic,
em.contractEmployeeHRA,
em.contractEmployeeBasketAllowance,
em.employeeBankName,
em.employeeBankACNo,
em.employeeBankIFSCCode,
em.epfOrUanNo,
em.esiNo,

em.employeeFathersName employeeFathersName,
em.employeeRecruitTime employeeRecruitTime,
em.employeeMaritialStatus employeeMaritialStatus,
em.employeeLeprosyAffected employeeLeprosyAffected,
em.employeeLeprosyAffectedInFamily employeeLeprosyAffectedInFamily,
em.employeeStatus employeeStatus,
em.employeeAadharNo,
em.employeePanNo,
em.employeeEligibleforLeave,
em.employeeCasualLeave,
em.employeeSickLeave,
em.employeePriviledgeLeave,
em.employeeMaternityLeave,
em.employeeMiscarraigeLeave,
em.employeePaternityLeave,
em.employeeEligibleforOB,
em.employeeAnnualIncrement,
em.employeeLeaveEncashment,
em.employeeGratuity,
em.employeeHealthInsSelf,
em.employeeHealthInsSpouse,
em.employeeHealthInsChildren,
em.employeeAccidentInsSelf,
em.employeeAccidentInsSpouse,
em.employeeAccidentInsChildren,
em.employeeHealthCheckUpSelf,
em.employeeHealthCheckUpSpouse,
em.employeeHealthCheckUpChildren,
em.employeeMobileExpenses,
em.employeeTravelPolicy,
em.addressSameAsCurrent,
em.employeeLeaveCF,
em.organizationId,
em.locationId,
em.contractEmployeeSalaryType,
em.employeeBioDataFile


FROM
employee AS em,
address AS ad,
address AS oad,
designation AS dg,
department AS dep
WHERE
em.addressId = ad.id
AND em.optAddressId = oad.id
AND em.employeeDesignation = dg.id
AND em.employeeDepartment  = dep.id;